name: ImageFireworksReborn
main: org.golde.bukkit.imagefireworksreborn.Main
version: 1.0
authors: ["Eric Golde", "Peter Golde", "deantonious"]
description: "This is a port of the plugin ImageFireworks by deantonious (https://www.spigotmc.org/resources/imagefireworks.18932/) that I have ported to Spigot 1.11.2 and below, and have added new features. Thanks to deantonious for letting me take over and manage his project ยง4โค"
website: http://eric.golde.org/
commands:
   imagefireworks:
      description: Image Fireworks command
      usage: /<command>
      aliases: [imgfws, if, imagef, imgf, imgfw, imagefw]
      
permissions:
  imagefireworks.use:
    default: op
    description: Permission for /imagefireworks